title: <p align="center" style="color:black; font-size:28px; font-family:arial">Xin (David) Zhao</p>
logo: "images/lightblue.png?raw=true" 
description:  
  <p align="center">
  <a href="pdf/CV_APL_XinZhao.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/davidxzhao/">LinkedIn</a> |
  <a href="https://github.com/davidzhao1015">GitHub</a>
  </p>
  </br>
- Health Data Scientist<br>
- Microbiome Researcher<br>
- Food Microbiologist<br>
    
theme: jekyll-theme-minimal
