title: <h1 style="color:black; text-align:center; font-size:150%;">Xin (David) Zhao</h1>
logo: images/lightblue.png 
description:  
  <p align="center">
  <a href="pdf/fullCV_DavidXinZhao_Feb2023.pdf">CV</a> |
  <a href="https://www.linkedin.com/in/davidxzhao/">LinkedIn</a> |
  <a href="https://scholar.google.com/citations?user=OVK0_oAAAAAJ&hl=en">Google Scholar</a>
  </p>
  </br>
  <ul>
    <li>Health Data Scientist</li>
    <li>Microbiome Researcher</li>
    <li>Food Microbiologist</li>
 </ul>
theme: jekyll-theme-minimal
