title: Xin (David) Zhao
logo: images/lightblue.png
description:  
  <p align="center">
  <a href="pdf/CV_APL_XinZhao.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/davidxzhao/">LinkedIn</a> |
  <a href="https://github.com/davidzhao1015">GitHub</a>
  </p>
  <ul>
    <li>Health Data Scientist</li>
    <li>Microbiome Researcher</li>
    <li>Food Microbiologist</li>
 </ul>
theme: jekyll-theme-minimal
