title: <p align="center" style="color:black; font-size:28px">Xin (David) Zhao</p>

logo: <img src="https://github.com/davidzhao1015/DavidZhao_Portfolio/blob/3249f939d70ca0bcf2d6e1e719aaa6655a4486c5/images/Me_profile_bluegray.png" alt="profileMe">

description:  
  <p align="center">
  <a href="pdf/CV_APL_XinZhao.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/davidxzhao/">LinkedIn</a> |
  <a href="https://github.com/davidzhao1015">GitHub</a>
  </p>
  
  <p align="left" style="color:gray">
  Data scientist in precision health
  <br><br>
  Food Microbiologist
  <br><br>
  </p>
    
theme: jekyll-theme-minimal
