title: <p align="center"> Xin (David) Zhao </p>

logo: "images/profile_grey_davidzhao.png?raw=true" 

description:  
  <p align="center">
  <a href="pdf/CV_APL_XinZhao.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/davidxzhao/">LinkedIn</a> |
  <a href="https://github.com/davidzhao1015">GitHub</a>
  </p>
  
    <p align="justify">
  Data scientist specialized in the genomics, microbiome and public health areas
  <br><br>
  PhD in Food Microbiolgy
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
