title: Xin (David) Zhao # your name (or website title) here
logo: "images/profile_grey_davidzhao.png?raw=false" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Microbiome Data Scientist
  <br><br>
  PhD in Food Microbiology
  <br><br>
  <a href="https://www.linkedin.com/in/davidxzhao/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
