title: <p align="center" sytle="color:blue; font-size:17; font-weight:bold"> Xin (David) Zhao </p>

logo: "images/profile_grey_davidzhao.png?raw=true" 

description:  
  <p align="center">
  <a href="pdf/CV_APL_XinZhao.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/davidxzhao/">LinkedIn</a> |
  <a href="https://github.com/davidzhao1015">GitHub</a>
  </p>
  
  <p align="left">
  Data scientist specialized in microbial genomics and metagenomics for public health 
  <br>
  Postdoctoral Fellow in Microbiome Epidemiology at Department of Pediatrics, University of Alberta
  <br>
  PhD in Food Microbiolgy at Department of Food Science and Bioresources, University of Alberta 
  <br>
  </p>
  
theme: jekyll-theme-minimal
